version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory into the container's /app directory
      # This allows for live reloading when code changes
      - .:/app
    # Override the Dockerfile CMD for development to enable reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 